FROM mongo:3.4
COPY init.sh /data/init.sh
COPY initdb_indexkey /data/initdb_indexkey
COPY initdb_configserver /data/initdb_configserver
COPY initdb_shard1nxxx.json /data/initdb_shard1xxx.json
COPY initdb_shard2nxxx.json /data/initdb_shard2nxxx.json
