FROM mongo:3.4
COPY init.sh /data/init.sh
COPY initdb_indexkey.json /data/initdb_indexkey.json
COPY initdb_configserver.json /data/initdb_configserver.json
COPY initdb_shard1nxxx.json /data/initdb_shard1xxx.json
COPY initdb_shard2nxxx.json /data/initdb_shard2nxxx.json
